baseURL = "https://jddemonteverde.com"
languageCode = 'en-us'
title = 'JD DE MONTEVERDE'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "JD DE MONTEVERDE"
location = "Laguna, Philippines"
description = "Welcome to my website. This is where I showcase my projects and blogs about my thoughts, learnings, and experiences as a DevOps Engineer."
profile_image = "/images/profile.jpg"

# Social Media Links
github = "https://github.com/blanktorious"
email = "johnddemonteverde@gmail.com"
linkedin = "https://linkedin.com/in/jddemonteverde"

# Certifications
[[params.certifications]]
title = "Microsoft Certified: Azure Fundamentals"
date = "March 17, 2025"
url = "https://learn.microsoft.com/api/credentials/share/en-us/JDdeMonteverde-4880/46CEA199D64D82B?sharingId=FD2609815AA4B38F"

[menu]
  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 3